//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data sync fails.
        /// </summary>
        internal static string APPDATA_SYNC_FAIL {
            get {
                return ResourceManager.GetString("APPDATA_SYNC_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App data sync to server sucessfully.
        /// </summary>
        internal static string APPDATA_SYNC_SUCCESS {
            get {
                return ResourceManager.GetString("APPDATA_SYNC_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add customer, please try again.
        /// </summary>
        internal static string CUSTOMER_ADDED_FAIL {
            get {
                return ResourceManager.GetString("CUSTOMER_ADDED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer added successfully.
        /// </summary>
        internal static string CUSTOMER_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("CUSTOMER_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted successfully.
        /// </summary>
        internal static string CUSTOMER_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("CUSTOMER_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already Exists.
        /// </summary>
        internal static string CUSTOMER_EXIST_ERROR {
            get {
                return ResourceManager.GetString("CUSTOMER_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name already exists.
        /// </summary>
        internal static string CUSTOMER_NAME_EXIST_ERROR {
            get {
                return ResourceManager.GetString("CUSTOMER_NAME_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer updated successfully.
        /// </summary>
        internal static string CUSTOMER_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("CUSTOMER_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Equipment, please try again.
        /// </summary>
        internal static string EQUIPMENT_ADDING_FAIL {
            get {
                return ResourceManager.GetString("EQUIPMENT_ADDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment added successfully.
        /// </summary>
        internal static string EQUIPMENT_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment deleted successfully.
        /// </summary>
        internal static string EQUIPMENT_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment already Exists.
        /// </summary>
        internal static string EQUIPMENT_EXIST_ERROR {
            get {
                return ResourceManager.GetString("EQUIPMENT_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Name already exists.
        /// </summary>
        internal static string EQUIPMENT_NAME_EXIST_ERROR {
            get {
                return ResourceManager.GetString("EQUIPMENT_NAME_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment updated successfully.
        /// </summary>
        internal static string EQUIPMENT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("EQUIPMENT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error -fr.
        /// </summary>
        internal static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found, please contact your administrator.
        /// </summary>
        internal static string FORGOT_PASSWORD_MESSAGE_ERROR {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_MESSAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link sent to your email. .
        /// </summary>
        internal static string FORGOT_PASSWORD_MESSAGE_SUCCESS {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_MESSAGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Inspection, please try again.
        /// </summary>
        internal static string INSPECTION_ADDING_FAIL {
            get {
                return ResourceManager.GetString("INSPECTION_ADDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection added successfully.
        /// </summary>
        internal static string INSPECTION_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Deleted Successfully.
        /// </summary>
        internal static string INSPECTION_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection already Exists.
        /// </summary>
        internal static string INSPECTION_EXIST_ERROR {
            get {
                return ResourceManager.GetString("INSPECTION_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Sample, please try again.
        /// </summary>
        internal static string INSPECTION_SAMPLE_ADDING_FAIL {
            get {
                return ResourceManager.GetString("INSPECTION_SAMPLE_ADDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample added successfully.
        /// </summary>
        internal static string INSPECTION_SAMPLE_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_SAMPLE_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection sample deleted successfully.
        /// </summary>
        internal static string INSPECTION_SAMPLE_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_SAMPLE_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample updation fails.
        /// </summary>
        internal static string INSPECTION_SAMPLE_UPDATION_FAIL {
            get {
                return ResourceManager.GetString("INSPECTION_SAMPLE_UPDATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample updated successfully.
        /// </summary>
        internal static string INSPECTION_SAMPLE_UPDATION_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_SAMPLE_UPDATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection updated successfully.
        /// </summary>
        internal static string INSPECTION_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("INSPECTION_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type.
        /// </summary>
        internal static string INVALID_FILE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out successfully.
        /// </summary>
        internal static string LOGOUT_SUCCESS {
            get {
                return ResourceManager.GetString("LOGOUT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine added successfully.
        /// </summary>
        internal static string MACHINE_ADDED_SUCCESS {
            get {
                return ResourceManager.GetString("MACHINE_ADDED_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine to add Site, please try again.
        /// </summary>
        internal static string MACHINE_ADDING_FAIL {
            get {
                return ResourceManager.GetString("MACHINE_ADDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine deleted successfully.
        /// </summary>
        internal static string MACHINE_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MACHINE_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine already Exists.
        /// </summary>
        internal static string MACHINE_EXIST_ERROR {
            get {
                return ResourceManager.GetString("MACHINE_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name already exists.
        /// </summary>
        internal static string MACHINE_NAME_EXIST_ERROR {
            get {
                return ResourceManager.GetString("MACHINE_NAME_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine updated successfully.
        /// </summary>
        internal static string MACHINE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MACHINE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully marked as read.
        /// </summary>
        internal static string NOTIFICATION_MARK_AS_READ_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFICATION_MARK_AS_READ_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part measurements updated Fails.
        /// </summary>
        internal static string PARTMEASUREMENTS_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("PARTMEASUREMENTS_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part measurements updated successfully.
        /// </summary>
        internal static string PARTMEASUREMENTS_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("PARTMEASUREMENTS_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update password.
        /// </summary>
        internal static string PASSWORD_RESET_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        internal static string PASSWORD_RESET_SUCCESS {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture updated successfully.
        /// </summary>
        internal static string PROFILE_PICTURE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("PROFILE_PICTURE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter missing -fr.
        /// </summary>
        internal static string REQUIRED_PARAMETER_MISSING {
            get {
                return ResourceManager.GetString("REQUIRED_PARAMETER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Site, please try again.
        /// </summary>
        internal static string SITE_ADDING_FAIL {
            get {
                return ResourceManager.GetString("SITE_ADDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site added successfully.
        /// </summary>
        internal static string SITE_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("SITE_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site deleted Successfully.
        /// </summary>
        internal static string SITE_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("SITE_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site already Exists.
        /// </summary>
        internal static string SITE_EXIST_ERROR {
            get {
                return ResourceManager.GetString("SITE_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name already exists.
        /// </summary>
        internal static string SITE_NAME_EXIST_ERROR {
            get {
                return ResourceManager.GetString("SITE_NAME_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site updated successfully.
        /// </summary>
        internal static string SITE_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("SITE_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS_TITLE {
            get {
                return ResourceManager.GetString("SUCCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user, please try again.
        /// </summary>
        internal static string USER_ADDED_FAIL {
            get {
                return ResourceManager.GetString("USER_ADDED_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully.
        /// </summary>
        internal static string USER_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string USER_CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        internal static string USER_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        internal static string USER_EMAIL_EXIST_ERROR {
            get {
                return ResourceManager.GetString("USER_EMAIL_EXIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;background:#083069;padding:10px;&quot;&gt;
        ///    &lt;img src=&quot;{logoUrl}&quot; /&gt;&lt;/div&gt;&lt;br /&gt;&lt;br /&gt;
        ///    &lt;div style=&quot;border-top:3px solid #22BCE5&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///    &lt;span style=&quot;font-family:Arial;font-size:10pt&quot;&gt;
        ///        Dear &lt;b&gt;{UserName}&lt;/b&gt;,&lt;br /&gt;&lt;br /&gt;
        ///       You have indicated that you must reset your password.  Please click below to reset your password.
        ///&lt;br/&gt;&lt;br/&gt;
        /// &lt;a style=&quot;color:#22BCE5&quot; href=&quot;{Url}&quot;&gt;Reset Passw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USER_FORGOT_PASSWORD_BODY {
            get {
                return ResourceManager.GetString("USER_FORGOT_PASSWORD_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bradken Inspect - Forgot password.
        /// </summary>
        internal static string USER_FORGOT_PASSWORD_SUBJECT {
            get {
                return ResourceManager.GetString("USER_FORGOT_PASSWORD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;background:#083069;padding:10px;&quot;&gt;
        ///    &lt;img src=&quot;{logoUrl}&quot; /&gt;&lt;/div&gt;&lt;br /&gt;&lt;br /&gt;
        ///    &lt;div style=&quot;border-top:3px solid #22BCE5&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///    &lt;span style=&quot;font-family:Arial;font-size:10pt&quot;&gt;
        ///        Dear &lt;b&gt;{UserName}&lt;/b&gt;,&lt;br /&gt;&lt;br /&gt;
        ///        You have been added as a user to the Bradken Inspect application. 
        ///&lt;br/&gt;&lt;br/&gt;
        ///
        ///Please click the link below to set your password.&lt;br/&gt;
        /// &lt;a style=&quot;color:#22BC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string USER_INVITE_EMAIL_BODY {
            get {
                return ResourceManager.GetString("USER_INVITE_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bradken Inspect - App Invitation.
        /// </summary>
        internal static string USER_INVITE_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("USER_INVITE_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        internal static string USER_LOGIN_EMAIL_NOT_MATCHED {
            get {
                return ResourceManager.GetString("USER_LOGIN_EMAIL_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not verified.
        /// </summary>
        internal static string USER_LOGIN_EMAIL_NOT_VERIFIED {
            get {
                return ResourceManager.GetString("USER_LOGIN_EMAIL_NOT_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive, please contact your administrator.
        /// </summary>
        internal static string USER_LOGIN_INACTIVE_USER {
            get {
                return ResourceManager.GetString("USER_LOGIN_INACTIVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tried maximum attempt for login, please contact you administrator.
        /// </summary>
        internal static string USER_LOGIN_MAX_ATTEMPT_RITCHED {
            get {
                return ResourceManager.GetString("USER_LOGIN_MAX_ATTEMPT_RITCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string USER_LOGIN_PASSWORD_NOT_MATCHED {
            get {
                return ResourceManager.GetString("USER_LOGIN_PASSWORD_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string USER_LOGIN_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("USER_LOGIN_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        internal static string USER_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("USER_UPDATE_SUCCESS", resourceCulture);
            }
        }
    }
}
